version: "3"
services:
  web:
    build: ./
    volumes:
      - ./php//php.ini:/usr/local/etc/php/php.ini
      - ./html:/var/www/html
    ports:
      - 8080:80
    extra_hosts:
      - "host.docker.internal:host-gateway"
